import fs from 'node:fs'
import path from 'node:path'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

const publicSite = (process.env.VITE_PUBLIC_SITE_URL || '').trim().replace(/\/$/, '')

/** يولّد `dist/sw.js` بعد البناء مع ذِكر أصول الـ JS/CSS المُجزّأة للتخزين المؤقت */
function pwaGenerateSwPlugin(): Plugin {
  return {
    name: 'pwa-generate-sw',
    apply: 'build',
    closeBundle() {
      const outDir = path.resolve(process.cwd(), 'dist')
      const assetsDir = path.join(outDir, 'assets')
      if (!fs.existsSync(assetsDir)) return

      const files = fs.readdirSync(assetsDir)
      const entryJs = files.find((f) => /^index-.*\.js$/i.test(f))
      const entryCss = files.find((f) => /^index-.*\.css$/i.test(f))

      const precache: string[] = [
        '/index.html',
        '/manifest.webmanifest',
        '/site-logo.jpg',
        '/favicon.svg',
      ]
      if (entryJs) precache.push(`/assets/${entryJs}`)
      if (entryCss) precache.push(`/assets/${entryCss}`)

      const cacheName = 'victorian-store-v3'
      const precacheJson = JSON.stringify(precache)
      const cacheJson = JSON.stringify(cacheName)

      const sw = `// generated by vite (pwa-generate-sw)
const CACHE = ${cacheJson};
const PRECACHE = ${precacheJson};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) =>
        Promise.all(PRECACHE.map((url) => cache.add(url).catch(() => undefined))),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // لا تخزن مؤقتاً: الـ API وملفات الرفع — يمنع تخزين index.html أو JSON خطأً كصورة
  if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/uploads/')) {
    event.respondWith(fetch(request));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match('/index.html')));
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return res;
      });
    }),
  );
});

// ── Web Push: استقبال إشعار طلب جديد وعرضه ──
self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try { data = event.data.json(); } catch { data = { title: 'إشعار', body: event.data.text() }; }
  }
  const title = data.title || 'إشعار جديد';
  const options = {
    body: data.body || '',
    icon: '/site-logo.jpg',
    badge: '/favicon.svg',
    tag: data.tag || 'order',
    renotify: true,
    requireInteraction: true,
    data: { url: data.url || '/admin' },
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

// عند النقر على الإشعار: افتح رابط الطلب أو ركّز نافذة موجودة
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || '/admin';
  event.waitUntil((async () => {
    const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of all) {
      try {
        const u = new URL(client.url);
        if (u.origin === self.location.origin) {
          await client.focus();
          if ('navigate' in client) {
            try { await client.navigate(target); } catch {}
          }
          return;
        }
      } catch {}
    }
    await self.clients.openWindow(target);
  })());
});
`
      fs.writeFileSync(path.join(outDir, 'sw.js'), sw, 'utf8')
    },
  }
}

export default defineConfig({
  plugins: [
    react(),
    {
      name: 'absolute-default-og-image',
      transformIndexHtml(html) {
        if (!publicSite) return html
        return html.replace(
          /<meta\s+property="og:image"\s+content="\/site-logo\.jpg"\s*\/>/,
          `<meta property="og:image" content="${publicSite}/site-logo.jpg" />`,
        )
      },
    },
    pwaGenerateSwPlugin(),
  ],
  server: {
    proxy: {
      '/api': { target: 'http://localhost:3001', changeOrigin: true },
    },
  },
})
